-- Migration: partner universities — batch 2 (everything except Australia & New Zealand, which batch 1 loaded)
-- Timestamp: 20260924130000
-- 418 schools across 24 regions; with batch 1 (34) that is the full 452 partner list.
-- Idempotent: a school is skipped if the same name already exists for that country.

-- Countries that only appear under "OTHERS"
WITH c(name, code, flag, ord) AS (VALUES
  ('Grenada',    'GD', '🇬🇩', 28),
  ('Uzbekistan', 'UZ', '🇺🇿', 29)
)
INSERT INTO public.study_countries (name, code, flag_emoji, display_order, is_featured, is_active)
SELECT c.name, c.code, c.flag, c.ord, false, true
FROM c
WHERE NOT EXISTS (SELECT 1 FROM public.study_countries s WHERE lower(s.name) = lower(c.name));

WITH u(name, country, region, ord) AS (VALUES
  ('Adler University', 'Canada', 'CANADA', 201),
  ('Alexander College', 'Canada', 'CANADA', 202),
  ('Bow Valley College', 'Canada', 'CANADA', 203),
  ('Birmingham International Collegiate', 'Canada', 'CANADA', 204),
  ('Braemar College', 'Canada', 'CANADA', 205),
  ('British Columbia Institute of Technology', 'Canada', 'CANADA', 206),
  ('Brock University', 'Canada', 'CANADA', 207),
  ('Canadian Tourism College', 'Canada', 'CANADA', 208),
  ('Capilano University', 'Canada', 'CANADA', 209),
  ('Cambria College', 'Canada', 'CANADA', 210),
  ('Centennial College', 'Canada', 'CANADA', 211),
  ('Durham College', 'Canada', 'CANADA', 212),
  ('Fraser International College', 'Canada', 'CANADA', 213),
  ('Herzing College', 'Canada', 'CANADA', 214),
  ('International Business University', 'Canada', 'CANADA', 215),
  ('Justice Institute of British Columbia', 'Canada', 'CANADA', 216),
  ('Kwantlen Polytechnic University', 'Canada', 'CANADA', 217),
  ('LaSalle College', 'Canada', 'CANADA', 218),
  ('MacEwan University', 'Canada', 'CANADA', 219),
  ('Merrick Preparatory School', 'Canada', 'CANADA', 220),
  ('Mount Saint Vincent University', 'Canada', 'CANADA', 221),
  ('Multihexa Carrer College', 'Canada', 'CANADA', 222),
  ('Niagara College Toronto', 'Canada', 'CANADA', 223),
  ('Northern College of Applied Arts and Technology', 'Canada', 'CANADA', 224),
  ('Ontario Tech University', 'Canada', 'CANADA', 225),
  ('Rotman Arts and Science School', 'Canada', 'CANADA', 226),
  ('Saskatchewan Polytechnic', 'Canada', 'CANADA', 227),
  ('Seneca Polytechnic', 'Canada', 'CANADA', 228),
  ('Sheridan College', 'Canada', 'CANADA', 229),
  ('Sobey School of Business (Saint Mary''s University)', 'Canada', 'CANADA', 230),
  ('Sprott School of Business (Carleton)', 'Canada', 'CANADA', 231),
  ('St. Lawrence College', 'Canada', 'CANADA', 232),
  ('Thompson Rivers University in British Columbia', 'Canada', 'CANADA', 233),
  ('Toronto Film School', 'Canada', 'CANADA', 234),
  ('Toronto School of Management', 'Canada', 'CANADA', 235),
  ('Trent University', 'Canada', 'CANADA', 236),
  ('Trinity Western University', 'Canada', 'CANADA', 237),
  ('University Canada West', 'Canada', 'CANADA', 238),
  ('University of Lethbridge', 'Canada', 'CANADA', 239),
  ('University of Niagara Falls', 'Canada', 'CANADA', 240),
  ('University of Northern British Columbia', 'Canada', 'CANADA', 241),
  ('University of Windsor', 'Canada', 'CANADA', 242),
  ('University of Winnipeg', 'Canada', 'CANADA', 243),
  ('University of Victoria', 'Canada', 'CANADA', 244),
  ('Wilfrid Laurier International College', 'Canada', 'CANADA', 245),
  ('Yorkville University', 'Canada', 'CANADA', 246),
  ('Adelphi University', 'United States', 'USA', 247),
  ('American Collegiate DC', 'United States', 'USA', 248),
  ('American Collegiate LA', 'United States', 'USA', 249),
  ('America University', 'United States', 'USA', 250),
  ('America University - Kogod Business School', 'United States', 'USA', 251),
  ('Arizona State University', 'United States', 'USA', 252),
  ('Ashland University', 'United States', 'USA', 253),
  ('Auburn University', 'United States', 'USA', 254),
  ('Avilla University', 'United States', 'USA', 255),
  ('Basis McLean School', 'United States', 'USA', 256),
  ('Bishop Montgomery High School', 'United States', 'USA', 257),
  ('California Lutheran University', 'United States', 'USA', 258),
  ('California State University', 'United States', 'USA', 259),
  ('Fullerton University', 'United States', 'USA', 260),
  ('Carmel Catholic High School', 'United States', 'USA', 261),
  ('Claremont Graduate University', 'United States', 'USA', 262),
  ('Clark University', 'United States', 'USA', 263),
  ('Cleveland State University', 'United States', 'USA', 264),
  ('College of San Mateo', 'United States', 'USA', 265),
  ('Concordia University', 'United States', 'USA', 266),
  ('Chicago University', 'United States', 'USA', 267),
  ('Cretin-Derham Hall High School', 'United States', 'USA', 268),
  ('DePaul University', 'United States', 'USA', 269),
  ('Drexel University', 'United States', 'USA', 270),
  ('Drew University', 'United States', 'USA', 271),
  ('Fairmont Preparatory Academy', 'United States', 'USA', 272),
  ('Florida International University', 'United States', 'USA', 273),
  ('Florida International University Graduate School of Business', 'United States', 'USA', 274),
  ('Fox School of Business and Management', 'United States', 'USA', 275),
  ('Gannon University', 'United States', 'USA', 276),
  ('George Mason University', 'United States', 'USA', 277),
  ('GO Program - Fisher College', 'United States', 'USA', 278),
  ('Gonzaga University', 'United States', 'USA', 279),
  ('Hofstra University', 'United States', 'USA', 280),
  ('Hult International Business School', 'United States', 'USA', 281),
  ('Illinois State University', 'United States', 'USA', 282),
  ('James Madison University', 'United States', 'USA', 283),
  ('Justin- Siena High School', 'United States', 'USA', 284),
  ('Keck Graduate Institute', 'United States', 'USA', 285),
  ('LIM College', 'United States', 'USA', 286),
  ('Lipscomb University', 'United States', 'USA', 287),
  ('Long Island University', 'United States', 'USA', 288),
  ('Long Island University Brooklyn', 'United States', 'USA', 289),
  ('Louisiana State University', 'United States', 'USA', 290),
  ('Marshall University', 'United States', 'USA', 291),
  ('Mater Dei Catholic High School', 'United States', 'USA', 292),
  ('Marist College', 'United States', 'USA', 293),
  ('Mercer University', 'United States', 'USA', 294),
  ('Miami University', 'United States', 'USA', 295),
  ('Mount Saint Vincent', 'United States', 'USA', 296),
  ('New York Institute of Technology', 'United States', 'USA', 297),
  ('North Broward Preparatory School', 'United States', 'USA', 298),
  ('Oregon State University', 'United States', 'USA', 299),
  ('Pace University', 'United States', 'USA', 300),
  ('Palm Beach Atlantic University', 'United States', 'USA', 301),
  ('Queens College', 'United States', 'USA', 302),
  ('Red Bank Catholic High School', 'United States', 'USA', 303),
  ('Saint Anthony''s High School', 'United States', 'USA', 304),
  ('Saint John''s High School', 'United States', 'USA', 305),
  ('Saint Peter''s University', 'United States', 'USA', 306),
  ('San Francisco State University', 'United States', 'USA', 307),
  ('Simmons University', 'United States', 'USA', 308),
  ('State University of New York at Geneseo', 'United States', 'USA', 309),
  ('St Louis University (INTO)', 'United States', 'USA', 310),
  ('St Mary''s College of California', 'United States', 'USA', 311),
  ('Stony Brook University (INTO)', 'United States', 'USA', 312),
  ('SUNY Geneseo', 'United States', 'USA', 313),
  ('Towson University', 'United States', 'USA', 314),
  ('Temple University', 'United States', 'USA', 315),
  ('Texas A&M University Corpus Christi', 'United States', 'USA', 316),
  ('The Gilbert School', 'United States', 'USA', 317),
  ('The Village School', 'United States', 'USA', 318),
  ('The Dave School- Digital Animation and Visual Effects School', 'United States', 'USA', 319),
  ('University Tulane University', 'United States', 'USA', 320),
  ('University of Alabama at Birmingham', 'United States', 'USA', 321),
  ('University of Arizona', 'United States', 'USA', 322),
  ('University of Central Florida', 'United States', 'USA', 323),
  ('University of Connecticut', 'United States', 'USA', 324),
  ('University of Dayton', 'United States', 'USA', 325),
  ('University of Delaware', 'United States', 'USA', 326),
  ('University of Hartford', 'United States', 'USA', 327),
  ('University of Illinois at Chicago', 'United States', 'USA', 328),
  ('University of Illinois Springfield', 'United States', 'USA', 329),
  ('University of Kansas', 'United States', 'USA', 330),
  ('University of Massachusetts Boston', 'United States', 'USA', 331),
  ('University of Mississippi', 'United States', 'USA', 332),
  ('University of New Haven', 'United States', 'USA', 333),
  ('University of Oklahoma (INTO)', 'United States', 'USA', 334),
  ('University of Texas San Antonio', 'United States', 'USA', 335),
  ('University of South Carolina', 'United States', 'USA', 336),
  ('University of the Pacific', 'United States', 'USA', 337),
  ('University of Utah', 'United States', 'USA', 338),
  ('University of Wyoming', 'United States', 'USA', 339),
  ('Waring School', 'United States', 'USA', 340),
  ('Washington State University', 'United States', 'USA', 341),
  ('Western New England University', 'United States', 'USA', 342),
  ('Woodside Priory School', 'United States', 'USA', 343),
  ('Windermere Preparatory', 'United States', 'USA', 344),
  ('Western Washington University', 'United States', 'USA', 345),
  ('Yamanashi Gakuin University', 'Japan', 'JAPAN', 346),
  ('Asia Pacific University', 'Malaysia', 'MALAYSIA', 347),
  ('Heriot-Watt Malaysia', 'Malaysia', 'MALAYSIA', 348),
  ('University of Wollongong', 'Malaysia', 'MALAYSIA', 349),
  ('University of Reading Malaysia', 'Malaysia', 'MALAYSIA', 350),
  ('East Asia Institute of Management EAIM', 'Singapore', 'SINGAPORE', 351),
  ('Curtin Singapore', 'Singapore', 'SINGAPORE', 352),
  ('James Cook University Singapore', 'Singapore', 'SINGAPORE', 353),
  ('Abu Dhabi University', 'United Arab Emirates', 'UAE', 354),
  ('American University of Dubai', 'United Arab Emirates', 'UAE', 355),
  ('Canadian University Dubai', 'United Arab Emirates', 'UAE', 356),
  ('De Montfort University Dubai', 'United Arab Emirates', 'UAE', 357),
  ('EM Normandie Business School', 'United Arab Emirates', 'UAE', 358),
  ('ES Dubai', 'United Arab Emirates', 'UAE', 359),
  ('FAD Institute of Luxury Fashion & Style', 'United Arab Emirates', 'UAE', 360),
  ('Global Banking School', 'United Arab Emirates', 'UAE', 361),
  ('Heriot-Watt University Dubai', 'United Arab Emirates', 'UAE', 362),
  ('Middlesex University Dubai', 'United Arab Emirates', 'UAE', 363),
  ('Murdoch University Dubai', 'United Arab Emirates', 'UAE', 364),
  ('Repton School in Dubai', 'United Arab Emirates', 'UAE', 365),
  ('Rochester Institute of Technology (RIT)', 'United Arab Emirates', 'UAE', 366),
  ('SAE Institute Dubai', 'United Arab Emirates', 'UAE', 367),
  ('University of Birmingham, Dubai', 'United Arab Emirates', 'UAE', 368),
  ('University of Stirling RAK', 'United Arab Emirates', 'UAE', 369),
  ('Dubai University of Wollongong', 'United Arab Emirates', 'UAE', 370),
  ('Webster University in Vienna', 'Austria', 'EUROPE - AUSTRIA', 371),
  ('UBI Business School', 'Belgium', 'EUROPE - BELGIUM', 372),
  ('European University Cyprus', 'Cyprus', 'EUROPE - CYPRUS', 373),
  ('Pascal Boarding School Cyprus', 'Cyprus', 'EUROPE - CYPRUS', 374),
  ('UCLAN Cyprus', 'Cyprus', 'EUROPE - CYPRUS', 375),
  ('University of Nicosia', 'Cyprus', 'EUROPE - CYPRUS', 376),
  ('University of Nicosia Medical School Foundation', 'Cyprus', 'EUROPE - CYPRUS', 377),
  ('Xenion Boarding School', 'Cyprus', 'EUROPE - CYPRUS', 378),
  ('University of New York in Prague', 'Czech Republic', 'EUROPE - CZECH REPUBLIC', 379),
  ('University of Vaasa', 'Finland', 'EUROPE - FINLAND', 380),
  ('3A-Entrepreneurship and Ethical Business', 'France', 'EUROPE - FRANCE', 381),
  ('Aivancity School of Technology, Business and Society', 'France', 'EUROPE - FRANCE', 382),
  ('Atelier Chardon Savard', 'France', 'EUROPE - FRANCE', 383),
  ('Atelier de Sevres', 'France', 'EUROPE - FRANCE', 384),
  ('CEFAM - International Business and Management', 'France', 'EUROPE - FRANCE', 385),
  ('CESI School of Engineering', 'France', 'EUROPE - FRANCE', 386),
  ('Cours Florent', 'France', 'EUROPE - FRANCE', 387),
  ('École de Management Appliqué', 'France', 'EUROPE - FRANCE', 388),
  ('EPSI - Computer Engineering', 'France', 'EUROPE - FRANCE', 389),
  ('ESAIL- Decoration & Interior Design', 'France', 'EUROPE - FRANCE', 390),
  ('ESAM - Corporate Finance & Strategic Management', 'France', 'EUROPE - FRANCE', 391),
  ('ICD- International Business School', 'France', 'EUROPE - FRANCE', 392),
  ('IDRAC Business School', 'France', 'EUROPE - FRANCE', 393),
  ('IEFT - Tourism and Hospitality Management', 'France', 'EUROPE - FRANCE', 394),
  ('ILERI - The School of International Relations', 'France', 'EUROPE - FRANCE', 395),
  ('IET - Institute of Environmental Technologies', 'France', 'EUROPE - FRANCE', 396),
  ('IESA Arts & CultureIESA Multimedia', 'France', 'EUROPE - FRANCE', 397),
  ('IFAG - Entrepreneurship & Innovation', 'France', 'EUROPE - FRANCE', 398),
  ('IGEFI - Accounting & Finance', 'France', 'EUROPE - FRANCE', 399),
  ('IHEDREA', 'France', 'EUROPE - FRANCE', 400),
  ('IMIS - Management of Health Industries', 'France', 'EUROPE - FRANCE', 401),
  ('Institut Cullinaire de France', 'France', 'EUROPE - FRANCE', 402),
  ('IPAG Business School', 'France', 'EUROPE - FRANCE', 403),
  ('Istituto Marangoni in Paris', 'France', 'EUROPE - FRANCE', 404),
  ('KEDGE Business School Paris', 'France', 'EUROPE - FRANCE', 405),
  ('LISAA', 'France', 'EUROPE - FRANCE', 406),
  ('MJM Graphic Design', 'France', 'EUROPE - FRANCE', 407),
  ('Paris School of Business', 'France', 'EUROPE - FRANCE', 408),
  ('Strate School of Design', 'France', 'EUROPE - FRANCE', 409),
  ('The American Business School of Paris', 'France', 'EUROPE - FRANCE', 410),
  ('Berlin School of Business & Innovation', 'Germany', 'EUROPE - GERMANY', 411),
  ('Constructor University', 'Germany', 'EUROPE - GERMANY', 412),
  ('EU Business School', 'Germany', 'EUROPE - GERMANY', 413),
  ('GISMA Business School', 'Germany', 'EUROPE - GERMANY', 414),
  ('International School of Management', 'Germany', 'EUROPE - GERMANY', 415),
  ('IU International University of Applied Sciences', 'Germany', 'EUROPE - GERMANY', 416),
  ('Lancaster University Leipzig', 'Germany', 'EUROPE - GERMANY', 417),
  ('Macromedia University of Applied Sciences', 'Germany', 'EUROPE - GERMANY', 418),
  ('PFH Private University of Applied Science', 'Germany', 'EUROPE - GERMANY', 419),
  ('SRH International College', 'Germany', 'EUROPE - GERMANY', 420),
  ('SRH Universities', 'Germany', 'EUROPE - GERMANY', 421),
  ('University of Europe for Applied Sciences', 'Germany', 'EUROPE - GERMANY', 422),
  ('Budapest Metropolitan University', 'Hungary', 'EUROPE - HUNGARY', 423),
  ('International Business School', 'Hungary', 'EUROPE - HUNGARY', 424),
  ('University of Debrecen', 'Hungary', 'EUROPE - HUNGARY', 425),
  ('Bologna Business School (University of Bologna)', 'Italy', 'EUROPE - ITALY', 426),
  ('DOMUS', 'Italy', 'EUROPE - ITALY', 427),
  ('Instituto Marangoni in Milan', 'Italy', 'EUROPE - ITALY', 428),
  ('John Cabot University', 'Italy', 'EUROPE - ITALY', 429),
  ('NABA Nuova Academia di Belle Arti Milano', 'Italy', 'EUROPE - ITALY', 430),
  ('Luiss University', 'Italy', 'EUROPE - ITALY', 431),
  ('Polimi Graduate School of Management', 'Italy', 'EUROPE - ITALY', 432),
  ('Politecnico di Milano', 'Italy', 'EUROPE - ITALY', 433),
  ('Università Vita-Salute San Raffaele', 'Italy', 'EUROPE - ITALY', 434),
  ('Global Banking School', 'Malta', 'EUROPE - MALTA', 435),
  ('London School of Commerce', 'Malta', 'EUROPE - MALTA', 436),
  ('Queen Mary University in Malta', 'Malta', 'EUROPE - MALTA', 437),
  ('Amsterdam Tech University', 'Netherlands', 'EUROPE - NETHERLANDS', 438),
  ('Holland International Study Centre', 'Netherlands', 'EUROPE - NETHERLANDS', 439),
  ('Intercollege Business School Amsterdam', 'Netherlands', 'EUROPE - NETHERLANDS', 440),
  ('The Hague University of Applied Sciences', 'Netherlands', 'EUROPE - NETHERLANDS', 441),
  ('Twente Pathway College', 'Netherlands', 'EUROPE - NETHERLANDS', 442),
  ('University of Amsterdam', 'Netherlands', 'EUROPE - NETHERLANDS', 443),
  ('Wittenborg University of Applied Sciences, Netherlands', 'Netherlands', 'EUROPE - NETHERLANDS', 444),
  ('Warsaw University of Business', 'Poland', 'EUROPE - POLAND', 445),
  ('ENAE International Business School', 'Spain', 'EUROPE - SPAIN & PORTUGAL', 446),
  ('ESIC University', 'Spain', 'EUROPE - SPAIN & PORTUGAL', 447),
  ('Euroinnova International Online Education', 'Spain', 'EUROPE - SPAIN & PORTUGAL', 448),
  ('GBSB Global Business School', 'Spain', 'EUROPE - SPAIN & PORTUGAL', 449),
  ('Instituto Quimico de Sarria', 'Spain', 'EUROPE - SPAIN & PORTUGAL', 450),
  ('LCI Barcelona', 'Spain', 'EUROPE - SPAIN & PORTUGAL', 451),
  ('Les Roches Marbella', 'Spain', 'EUROPE - SPAIN & PORTUGAL', 452),
  ('Porto Business School', 'Portugal', 'EUROPE - SPAIN & PORTUGAL', 453),
  ('UCAM Murcia University', 'Spain', 'EUROPE - SPAIN & PORTUGAL', 454),
  ('University Abat Oliba in Barcelona', 'Spain', 'EUROPE - SPAIN & PORTUGAL', 455),
  ('Universidad Cardenal Herrera in Valencia', 'Spain', 'EUROPE - SPAIN & PORTUGAL', 456),
  ('Universidad Nebrija', 'Spain', 'EUROPE - SPAIN & PORTUGAL', 457),
  ('Universidad San Pablo CEU in Madrid University', 'Spain', 'EUROPE - SPAIN & PORTUGAL', 458),
  ('Business Hotel Management School', 'Switzerland', 'EUROPE - SWITZERLAND', 459),
  ('College Champittet', 'Switzerland', 'EUROPE - SWITZERLAND', 460),
  ('EU Business School', 'Switzerland', 'EUROPE - SWITZERLAND', 461),
  ('Glion Switzerland', 'Switzerland', 'EUROPE - SWITZERLAND', 462),
  ('Le Roches Crans Montana', 'Switzerland', 'EUROPE - SWITZERLAND', 463),
  ('Atilim University', 'Turkey', 'EUROPE - TURKEY', 464),
  ('Istanbul Medipol University', 'Turkey', 'EUROPE - TURKEY', 465),
  ('KOC Turkey', 'Turkey', 'EUROPE - TURKEY', 466),
  ('Sabanci University', 'Turkey', 'EUROPE - TURKEY', 467),
  ('Abbey College Manchester', 'United Kingdom', 'UK & IRELAND', 468),
  ('Abbey DLD College London', 'United Kingdom', 'UK & IRELAND', 469),
  ('Abbey College Cambridge', 'United Kingdom', 'UK & IRELAND', 470),
  ('Aberystwyth University', 'United Kingdom', 'UK & IRELAND', 471),
  ('Anglia Ruskin University', 'United Kingdom', 'UK & IRELAND', 472),
  ('Arden University', 'United Kingdom', 'UK & IRELAND', 473),
  ('Arts University Bournemouth', 'United Kingdom', 'UK & IRELAND', 474),
  ('Aston University', 'United Kingdom', 'UK & IRELAND', 475),
  ('Bangor University', 'United Kingdom', 'UK & IRELAND', 476),
  ('Birkbeck, University of London', 'United Kingdom', 'UK & IRELAND', 477),
  ('Birmingham Newman University', 'United Kingdom', 'UK & IRELAND', 478),
  ('Bishopstrow College', 'United Kingdom', 'UK & IRELAND', 479),
  ('Bournemouth University', 'United Kingdom', 'UK & IRELAND', 480),
  ('Brunel University', 'United Kingdom', 'UK & IRELAND', 481),
  ('Buckinghamshire New University', 'United Kingdom', 'UK & IRELAND', 482),
  ('Canterbury Christ Church', 'United Kingdom', 'UK & IRELAND', 483),
  ('Cambridge School of Visual & Performing Arts – CSVP', 'United Kingdom', 'UK & IRELAND', 484),
  ('Cardiff University', 'United Kingdom', 'UK & IRELAND', 485),
  ('Cardiff Metropolitan University', 'United Kingdom', 'UK & IRELAND', 486),
  ('City University of London', 'United Kingdom', 'UK & IRELAND', 487),
  ('Circle International', 'United Kingdom', 'UK & IRELAND', 488),
  ('Coventry University', 'United Kingdom', 'UK & IRELAND', 489),
  ('Cardiff Sixth Form College', 'United Kingdom', 'UK & IRELAND', 490),
  ('David Game College London', 'United Kingdom', 'UK & IRELAND', 491),
  ('De Montfort University', 'United Kingdom', 'UK & IRELAND', 492),
  ('Dublin International College - DIFC', 'Ireland', 'UK & IRELAND', 493),
  ('Dublin City University', 'Ireland', 'UK & IRELAND', 494),
  ('Durham University', 'United Kingdom', 'UK & IRELAND', 495),
  ('d''Overbroeck''s Oxford', 'United Kingdom', 'UK & IRELAND', 496),
  ('Edinburgh Napier University', 'United Kingdom', 'UK & IRELAND', 497),
  ('Goldsmiths, University of London', 'United Kingdom', 'UK & IRELAND', 498),
  ('Griffith College', 'Ireland', 'UK & IRELAND', 499),
  ('Heriot-Watt University', 'United Kingdom', 'UK & IRELAND', 500),
  ('International Foundation Group', 'United Kingdom', 'UK & IRELAND', 501),
  ('Istituto Marangoni', 'United Kingdom', 'UK & IRELAND', 502),
  ('INTO City University of London', 'United Kingdom', 'UK & IRELAND', 503),
  ('INTO Lancaster University', 'United Kingdom', 'UK & IRELAND', 504),
  ('INTO London World Education Centre', 'United Kingdom', 'UK & IRELAND', 505),
  ('INTO Manchester (University of Manchester)', 'United Kingdom', 'UK & IRELAND', 506),
  ('INTO Newcastle University', 'United Kingdom', 'UK & IRELAND', 507),
  ('INTO Newton A Levels', 'United Kingdom', 'UK & IRELAND', 508),
  ('INTO Queen University Belfast', 'United Kingdom', 'UK & IRELAND', 509),
  ('INTO Stirling Scotland Education Centre', 'United Kingdom', 'UK & IRELAND', 510),
  ('INTO University of East Anglia', 'United Kingdom', 'UK & IRELAND', 511),
  ('INTO University of Exeter', 'United Kingdom', 'UK & IRELAND', 512),
  ('INTO University of Stirling', 'United Kingdom', 'UK & IRELAND', 513),
  ('Kaplan International College', 'United Kingdom', 'UK & IRELAND', 514),
  ('Keele University', 'United Kingdom', 'UK & IRELAND', 515),
  ('King''s College London (Online)', 'United Kingdom', 'UK & IRELAND', 516),
  ('Kings Bournemouth', 'United Kingdom', 'UK & IRELAND', 517),
  ('Kings Brighton', 'United Kingdom', 'UK & IRELAND', 518),
  ('Kings London', 'United Kingdom', 'UK & IRELAND', 519),
  ('Kings Oxford', 'United Kingdom', 'UK & IRELAND', 520),
  ('Lancaster University', 'United Kingdom', 'UK & IRELAND', 521),
  ('Leeds Beckett University', 'United Kingdom', 'UK & IRELAND', 522),
  ('Liverpool John Moores International Study Centre', 'United Kingdom', 'UK & IRELAND', 523),
  ('London Metropolitan University', 'United Kingdom', 'UK & IRELAND', 524),
  ('London South Bank University', 'United Kingdom', 'UK & IRELAND', 525),
  ('Loughborough University', 'United Kingdom', 'UK & IRELAND', 526),
  ('Manchester Metropolitan University', 'United Kingdom', 'UK & IRELAND', 527),
  ('Manchester Metropolitan University International College', 'United Kingdom', 'UK & IRELAND', 528),
  ('Manchester School of Architecture', 'United Kingdom', 'UK & IRELAND', 529),
  ('National College of Ireland', 'Ireland', 'UK & IRELAND', 530),
  ('Newcastle University', 'United Kingdom', 'UK & IRELAND', 531),
  ('NCUK International Study Centre', 'United Kingdom', 'UK & IRELAND', 532),
  ('Northumbria University', 'United Kingdom', 'UK & IRELAND', 533),
  ('Nottingham Trent University', 'United Kingdom', 'UK & IRELAND', 534),
  ('Oxford Brookes University', 'United Kingdom', 'UK & IRELAND', 535),
  ('Oxford International College', 'United Kingdom', 'UK & IRELAND', 536),
  ('Oxford Sixth Form College', 'United Kingdom', 'UK & IRELAND', 537),
  ('Padworth College', 'United Kingdom', 'UK & IRELAND', 538),
  ('ProEd', 'United Kingdom', 'UK & IRELAND', 539),
  ('Queen Ethelburga''s College', 'United Kingdom', 'UK & IRELAND', 540),
  ('Queen Mary University of London', 'United Kingdom', 'UK & IRELAND', 541),
  ('Queen''s University Belfast', 'United Kingdom', 'UK & IRELAND', 542),
  ('Robert Gordon University', 'United Kingdom', 'UK & IRELAND', 543),
  ('Royal Holloway, University of London', 'United Kingdom', 'UK & IRELAND', 544),
  ('Royal Veterinary College', 'United Kingdom', 'UK & IRELAND', 545),
  ('Royal College of Surgeons, Ireland (RCSI) - Foundation', 'Ireland', 'UK & IRELAND', 546),
  ('Roehampton University', 'United Kingdom', 'UK & IRELAND', 547),
  ('Ravensbourne University London', 'United Kingdom', 'UK & IRELAND', 548),
  ('Scotland''s Rural College (SRUC)', 'United Kingdom', 'UK & IRELAND', 549),
  ('Sheffield Hallam University', 'United Kingdom', 'UK & IRELAND', 550),
  ('SOAS University of London', 'United Kingdom', 'UK & IRELAND', 551),
  ('Solent University', 'United Kingdom', 'UK & IRELAND', 552),
  ('St. Andrew''s College Cambridge', 'United Kingdom', 'UK & IRELAND', 553),
  ('St Bees School', 'United Kingdom', 'UK & IRELAND', 554),
  ('Stover School', 'United Kingdom', 'UK & IRELAND', 555),
  ('Swansea University', 'United Kingdom', 'UK & IRELAND', 556),
  ('Technological University of the Shannon', 'Ireland', 'UK & IRELAND', 557),
  ('Teesside University', 'United Kingdom', 'UK & IRELAND', 558),
  ('The Courtauld Institute of Art', 'United Kingdom', 'UK & IRELAND', 559),
  ('The Royal School, Surrey', 'United Kingdom', 'UK & IRELAND', 560),
  ('The University of Nottingham', 'United Kingdom', 'UK & IRELAND', 561),
  ('Trinity College Dublin', 'Ireland', 'UK & IRELAND', 562),
  ('Ulster University', 'United Kingdom', 'UK & IRELAND', 563),
  ('University Academy 92 (Ua92)', 'United Kingdom', 'UK & IRELAND', 564),
  ('University College Cork', 'Ireland', 'UK & IRELAND', 565),
  ('University College Birmingham', 'United Kingdom', 'UK & IRELAND', 566),
  ('University College London (UCL)', 'United Kingdom', 'UK & IRELAND', 567),
  ('University of the Creative Arts', 'United Kingdom', 'UK & IRELAND', 568),
  ('University of Aberdeen', 'United Kingdom', 'UK & IRELAND', 569),
  ('University of Bath', 'United Kingdom', 'UK & IRELAND', 570),
  ('University of Birmingham', 'United Kingdom', 'UK & IRELAND', 571),
  ('University of Bradford', 'United Kingdom', 'UK & IRELAND', 572),
  ('University of Brighton', 'United Kingdom', 'UK & IRELAND', 573),
  ('University of Bristol', 'United Kingdom', 'UK & IRELAND', 574),
  ('University of Central Lancashire (UCLan)', 'United Kingdom', 'UK & IRELAND', 575),
  ('University of Chester', 'United Kingdom', 'UK & IRELAND', 576),
  ('University of Cumbria', 'United Kingdom', 'UK & IRELAND', 577),
  ('University of Derby', 'United Kingdom', 'UK & IRELAND', 578),
  ('University of Dundee', 'United Kingdom', 'UK & IRELAND', 579),
  ('University of East Anglia', 'United Kingdom', 'UK & IRELAND', 580),
  ('University of Essex', 'United Kingdom', 'UK & IRELAND', 581),
  ('University of Galway', 'Ireland', 'UK & IRELAND', 582),
  ('University of Glasgow', 'United Kingdom', 'UK & IRELAND', 583),
  ('University of Gloucestershire', 'United Kingdom', 'UK & IRELAND', 584),
  ('University of Greenwich', 'United Kingdom', 'UK & IRELAND', 585),
  ('University of Huddersfield', 'United Kingdom', 'UK & IRELAND', 586),
  ('University of Hertfordshire', 'United Kingdom', 'UK & IRELAND', 587),
  ('University of Hull', 'United Kingdom', 'UK & IRELAND', 588),
  ('University of Kent', 'United Kingdom', 'UK & IRELAND', 589),
  ('University of Law', 'United Kingdom', 'UK & IRELAND', 590),
  ('University of Lancaster', 'United Kingdom', 'UK & IRELAND', 591),
  ('University of Leicester', 'United Kingdom', 'UK & IRELAND', 592),
  ('University of Leeds International Study Centre', 'United Kingdom', 'UK & IRELAND', 593),
  ('University of Liverpool', 'United Kingdom', 'UK & IRELAND', 594),
  ('University of Limerick', 'Ireland', 'UK & IRELAND', 595),
  ('University of Lincoln', 'United Kingdom', 'UK & IRELAND', 596),
  ('University of Northampton', 'United Kingdom', 'UK & IRELAND', 597),
  ('University of Plymouth', 'United Kingdom', 'UK & IRELAND', 598),
  ('University of Portsmouth', 'United Kingdom', 'UK & IRELAND', 599),
  ('University of Reading', 'United Kingdom', 'UK & IRELAND', 600),
  ('University of Southampton', 'United Kingdom', 'UK & IRELAND', 601),
  ('University of South Wales', 'United Kingdom', 'UK & IRELAND', 602),
  ('University of Suffolk', 'United Kingdom', 'UK & IRELAND', 603),
  ('University of Sunderland', 'United Kingdom', 'UK & IRELAND', 604),
  ('University of Staffordshire', 'United Kingdom', 'UK & IRELAND', 605),
  ('University of Stirling', 'United Kingdom', 'UK & IRELAND', 606),
  ('University of Strathclyde', 'United Kingdom', 'UK & IRELAND', 607),
  ('University of Surrey', 'United Kingdom', 'UK & IRELAND', 608),
  ('University of Sussex', 'United Kingdom', 'UK & IRELAND', 609),
  ('University of the West of England', 'United Kingdom', 'UK & IRELAND', 610),
  ('University of Westminster', 'United Kingdom', 'UK & IRELAND', 611),
  ('University of Wolverhampton', 'United Kingdom', 'UK & IRELAND', 612),
  ('University of Wolverhampton International Study Center', 'United Kingdom', 'UK & IRELAND', 613),
  ('University of Worcester', 'United Kingdom', 'UK & IRELAND', 614),
  ('University of York', 'United Kingdom', 'UK & IRELAND', 615),
  ('University of Nottingham Ningbo', 'China', 'CHINA', 616),
  ('St George''s University', 'Grenada', 'OTHERS', 617),
  ('Westminster International University Tashkent', 'Uzbekistan', 'OTHERS', 618)
)
INSERT INTO public.universities (name, country_id, region, is_partner, is_active, display_order)
SELECT u.name, sc.id, u.region, true, true, u.ord
FROM u
JOIN public.study_countries sc ON lower(sc.name) = lower(u.country)
WHERE NOT EXISTS (
  SELECT 1 FROM public.universities x
  WHERE lower(x.name) = lower(u.name) AND x.country_id = sc.id
);

-- Sanity check (shows in the CLI output as a NOTICE): expect 452 partner universities with a region
DO $$
DECLARE n INTEGER;
BEGIN
  SELECT count(*) INTO n FROM public.universities WHERE is_partner AND region IS NOT NULL;
  RAISE NOTICE 'Partner universities with a region: %', n;
END $$;
